### ISSUE TITLE
Add an option to reset the slugger after each document.

### ISSUE THREAD

**Issue by ghost** [Flet/markdown-it-github-headings#11]
When parsing multiple documents through the same *markdown-it* instance, the slugs are incremented.

```js
const markdown = require("markdown-it")()
    .use(require('markdown-it-github-headings'));
markdown.parse("# Hello World"); // id = "hello-world"
markdown.parse("# Hello World"); // id = "hello-world-1"
markdown.parse("# Hello World"); // id = "hello-world-2"
```

A missing option would be to [reset the slugger](https://github.com/Flet/github-slugger#usage) like it's done in [other markdown-it plugins](https://github.com/yuki-takei/markdown-it-toc-and-anchor-with-slugid#resetids).

```js
const markdown = require("markdown-it")()
    .use(require('markdown-it-github-headings', {resetIds: true}));
markdown.parse("# Hello World"); // id = "hello-world"
markdown.parse("# Hello World"); // id = "hello-world"
markdown.parse("# Hello World"); // id = "hello-world"
```

Having this option defaulting to `false` won't break current implementations while giving the ability to use a single *markdown-it* instance for parsing as optimisation.

**Comment by Flet** [comment]
This looks like a good idea!

**Comment by niftylettuce** [comment]
Related to #13

**Comment by niftylettuce** [comment]
I would gladly donate a bug bounty reward to the first person to resolve this issue. 🐛 💰 

cc @Flet

**Comment by Flet** [comment]
Totally! I am not actively using this package, but I'm happy to review/publish I'd someone wants to tackle it. Do you have a bounty site you prefer to use @niftylettuce? I'm happy to pitch in a few bucks for this too.

**Comment by niftylettuce** [comment]
I just use PayPal.  I'm offering $50 to the first person to submit a working PR to resolve this.

**Comment by Flet** [comment]
Published as `markdown-it-github-headings@2.0.0`

**Comment by niftylettuce** [comment]
What's your PayPal @Flet 	?

**Comment by niftylettuce** [comment]
Also @Flet 	- I can confirm this works.  Thank you.  I will be using it on the next deployment to https://forwardemail.net.

**Comment by Flet** [comment]
No worries, @niftylettuce! Keep your money :) 

https://forwardemail.net looks cool! I'll give it a try. Happy to help make it better in a tiny way ;)
