### ISSUE TITLE
Customizing the icon

### ISSUE THREAD

**Issue by adam-lynch** [Flet/markdown-it-github-headings#8]
I wanted to use a different icon and I noticed that I could do this:

```javascript
    const githubHeadings = require('markdown-it-github-headings')
    githubHeadings.svgLinkIconText = '<svg...> ... </svg>'

    marked.use(githubHeadings, {
        // ...
    })
```

I could create a pull-request to add this to the docs? Or I can add an option for it?

**Comment by Flet** [comment]
Yeah go for it! As long as the default behavior is the same it will be accepted :)
